name: Sourcegraph Node LSIF Indexer
description: Generate LSIF data from TypeScript source code
author: Sourcegraph
branding:
  icon: code
  color: purple

inputs:
  file:
    description: The output filename.
    default: data.lsif
  project_root: 
    description: The project root.
    default: .
  verbose:
    description: Set to true to log indexer progress
    default: ''

runs:
  using: docker
  image: Dockerfile
  env:
    OUT: ${{ inputs.file }}
    PROJECT_ROOT: ${{ inputs.project_root }}
    VERBOSE: ${{ inputs.verbose }}
