name: Sourcegraph TypeScript LSIF Indexer
description: Generate LSIF data from TypeScript source code
author: Sourcegraph
branding:
  icon: code
  color: purple

inputs:
  file:
    description: The output filename.
    default: dump.lsif
  project_root: 
    description: The root of the project (where tsconfig.json is located).
    default: .

runs:
  using: docker
  image: Dockerfile
  env:
    OUT: ${{ inputs.file }}
    PROJECT_ROOT: ${{ inputs.project_root }}
